from typing import List

from telegram import BotCommand, Update
from telegram.ext import ContextTypes

from db.access import has_full_access


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message is None:
        return
    await update.message.reply_text(
        "Welcome to SignalRankAI.\n\n"
        "Not financial advice. Trading involves risk.\n\n"
        "Commands: /help /pricing /upgrade /signals",
    )


async def help_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message is None:
        return
    await update.message.reply_text(
        "/start — start\n"
        "/help — help\n"
        "/pricing — plans\n"
        "/upgrade — how to upgrade\n"
        "/signals — latest signals\n"
        "/stats — (Premium) performance\n"
        "/history — (Premium) history",
    )


async def pricing(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message is None:
        return
    await update.message.reply_text(
        "SignalRankAI Plans\n"
        "• Free: limited daily summary\n"
        "• Premium: full signals + TP/SL alerts\n"
        "• VIP: higher priority signals + faster alerts\n\n"
        "Use /upgrade to subscribe.",
    )


async def upgrade(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    # In production: point to FastAPI endpoint that creates Paystack payment link.
    if update.message is None:
        return
    await update.message.reply_text(
        "To upgrade, follow the payment link generated by the bot admin.\n"
        "(Payment automation will be wired to /webhooks/paystack)",
    )


async def stats(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.effective_user is None or update.message is None:
        return
    user_id = update.effective_user.id
    if not await has_full_access(user_id):
        await update.message.reply_text("🔒 Premium required. Use /upgrade.")
        return
    await update.message.reply_text("(Stub) Detailed stats will appear here.")


async def history(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.effective_user is None or update.message is None:
        return
    user_id = update.effective_user.id
    if not await has_full_access(user_id):
        await update.message.reply_text("🔒 Premium required. Use /upgrade.")
        return
    await update.message.reply_text("(Stub) Signal history will appear here.")


def public_commands() -> List[BotCommand]:
    return [
        BotCommand("start", "Start the bot"),
        BotCommand("help", "Help"),
        BotCommand("pricing", "View plans"),
        BotCommand("upgrade", "Upgrade your plan"),
        BotCommand("signals", "Latest signals"),
        BotCommand("stats", "(Premium) performance"),
        BotCommand("history", "(Premium) history"),
    ]
