FROM hadolint/hadolint:v2.12.0-debian
WORKDIR /workspace
COPY Dockerfile /workspace/Dockerfile
RUN hadolint --failure-threshold warning /workspace/Dockerfile
CMD ["sh","-c","echo SIGNALRANK_HADOLINT_PASS; sleep 600"]
