[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python -m alembic upgrade head || true"]

[start]
cmd = "python main.py"
