"""Environment-parity feature registry tests (Phase 9).

Every advertised command must have exactly one registered handler, every
callback-data value generated by a keyboard must match at least one registered
callback pattern, and specific callbacks must not be swallowed by the generic
handler before their intended handler.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _bot_source() -> str:
    return (ROOT / "signalrank_telegram" / "bot.py").read_text(encoding="utf-8-sig")


def _handler_command_name(call: ast.Call) -> str | None:
    """Return the command name for a CommandHandler(...) call, else None."""
    if not call.args:
        return None
    first = call.args[0]
    if isinstance(first, ast.Constant) and isinstance(first.value, str):
        return first.value
    return None


def _registered_commands() -> dict[str, int]:
    """Map command name -> effective registration count via AST.

    A command registered once in a ``try`` body and once in its ``except``
    fallback is mutually exclusive at runtime (either the real handler or the
    degraded fallback is active) and counts as a single logical registration.
    """
    tree = ast.parse(_bot_source(), filename="bot.py")
    counts: dict[str, int] = {}
    handler_calls: list[ast.Call] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        is_command_handler = False
        if isinstance(func, ast.Name):
            is_command_handler = func.id == "CommandHandler"
        elif isinstance(func, ast.Attribute):
            is_command_handler = func.attr == "CommandHandler"
        if is_command_handler:
            handler_calls.append(node)

    # Identify try/except pairs that register the same command in both bodies.
    try_names: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Try):
            continue
        try_calls = [
            call for call in handler_calls if _inside(call, node.body)
        ]
        except_calls = [
            call for call in handler_calls if _inside(call, node.handlers[0].body)
        ] if node.handlers else []
        try_cmd = {name for call in try_calls if (name := _handler_command_name(call))}
        except_cmd = {name for call in except_calls if (name := _handler_command_name(call))}
        try_names |= (try_cmd & except_cmd)

    for call in handler_calls:
        name = _handler_command_name(call)
        if name is None:
            continue
        # The except-fallback registration is the second of an exclusive pair;
        # the try body is the primary. Count the pair once (at the try site).
        if name in try_names and _in_except_block(call, tree):
            continue
        counts[name] = counts.get(name, 0) + 1
    return counts


def _inside(call: ast.Call, body: list[ast.stmt]) -> bool:
    call_lineno = call.lineno
    return any(
        getattr(stmt, "lineno", -1) <= call_lineno <= getattr(stmt, "end_lineno", -1)
        for stmt in body
    )


def _in_except_block(call: ast.Call, tree: ast.Module) -> bool:
    for node in ast.walk(tree):
        if not isinstance(node, ast.Try) or not node.handlers:
            continue
        if _inside(call, node.handlers[0].body):
            return True
    return False


def _catalogue_commands() -> set[str]:
    from signalrank_telegram.command_catalog import COMMANDS

    return {spec.name for spec in COMMANDS}


def _constant_str(value: ast.expr) -> str | None:
    """Flatten a constant, tuple-of-constants, or joined-string to a pattern."""
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    if isinstance(value, ast.JoinedStr):
        parts: list[str] = []
        for part in value.values:
            if isinstance(part, ast.Constant) and isinstance(part.value, str):
                parts.append(part.value)
            elif isinstance(part, ast.FormattedValue):
                return None
        return "".join(parts)
    if isinstance(value, ast.Tuple):
        parts = []
        for element in value.elts:
            flattened = _constant_str(element)
            if flattened is None:
                return None
            parts.append(flattened)
        return "".join(parts)
    if isinstance(value, ast.BinOp) and isinstance(value.op, ast.Add):
        left = _constant_str(value.left)
        right = _constant_str(value.right)
        if left is None or right is None:
            return None
        return left + right
    return None


def _registered_callback_patterns() -> list[tuple[str, str]]:
    """Return (name, pattern) pairs from add_handler(CallbackQueryHandler...)."""
    tree = ast.parse(_bot_source(), filename="bot.py")
    out: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        is_cqh = False
        if isinstance(func, ast.Name):
            is_cqh = func.id == "CallbackQueryHandler" or func.id.startswith("_CQH")
        elif isinstance(func, ast.Attribute):
            is_cqh = func.attr == "CallbackQueryHandler" or func.attr.startswith("_CQH")
        if not is_cqh or not node.args:
            continue
        pattern = None
        handler_name = None
        for keyword in node.keywords:
            if keyword.arg == "pattern":
                pattern = _constant_str(keyword.value)
        if node.args and isinstance(node.args[0], ast.Call) and isinstance(node.args[0].func, ast.Name):
            handler_name = node.args[0].func.id
        if pattern:
            out.append((handler_name or "?", pattern))
    return out


def _callback_patterns_from_module() -> dict[str, str]:
    from signalrank_telegram.callback_handlers import CALLBACK_PATTERNS

    return dict(CALLBACK_PATTERNS)


def test_every_catalogue_command_has_exactly_one_handler() -> None:
    registered = _registered_commands()
    catalogue = _catalogue_commands()

    missing = sorted(catalogue - set(registered))
    assert not missing, f"commands advertised but never registered: {missing}"

    duplicates = sorted(name for name, count in registered.items() if count > 1)
    assert not duplicates, f"commands registered more than once: {duplicates}"


def test_callback_patterns_are_registered_before_generic_handler() -> None:
    source = _bot_source()
    # The subscription checkout callback must be registered before the global
    # catch-all router so it is never swallowed.
    subscribe_pos = source.find("subscribe:premium")
    generic_pos = source.find("create_global_callback_handler")
    if subscribe_pos >= 0 and generic_pos >= 0:
        assert subscribe_pos < generic_pos, (
            "subscribe: callback must be registered before the generic catch-all handler"
        )


def test_generated_callback_values_match_registered_patterns() -> None:
    """Every subscribe: callback emitted by the upgrade menu matches a handler."""
    from payments.plan_catalogue import get_plan_catalogue

    registered = _registered_callback_patterns()
    # The canonical subscribe handler is registered with a pattern that matches
    # every plan code in the authoritative catalogue.
    patterns = [pattern for _name, pattern in registered if "subscribe" in pattern]
    assert patterns, "subscribe: callback handler pattern not registered"

    catalogue = get_plan_catalogue()
    for plan_code in catalogue:
        callback = f"subscribe:{plan_code}"
        assert any(
            re.match(pattern, callback) for pattern in patterns
        ), f"plan callback {callback!r} has no registered handler"
    # The catalogue key must equal the plan's own code field.
    for plan_code, plan in catalogue.items():
        assert plan.code == plan_code


def test_global_fallback_does_not_claim_specific_callbacks() -> None:
    """The global catch-all must be registered last (after specific handlers)."""
    source = _bot_source()
    # Specific handlers are registered between the fast-ack section and the
    # global fallback. Verify the fallback appears after the specific ones.
    fast_ack = source.find("CallbackQueryHandler as _CQH_fast_ack")
    fallback = source.find("create_global_callback_handler")
    assert fallback > fast_ack, "global callback handler must be registered after specific handlers"


def test_botfather_catalogue_entries_are_registered() -> None:
    from signalrank_telegram.command_catalog import botfather_commands

    advertised = {name for name, _desc in botfather_commands("FREE")}
    registered = set(_registered_commands())
    missing = sorted(advertised - registered)
    assert not missing, f"botfather-advertised commands missing a handler: {missing}"


def test_upgrade_menu_plan_callbacks_are_deterministic() -> None:
    from payments.plan_catalogue import get_plan_catalogue

    catalogue = get_plan_catalogue()
    codes = set(catalogue)
    assert codes == {"premium_monthly", "premium_quarterly", "premium_yearly", "vip_monthly"}
    # Every plan has a price and a duration in the authoritative catalogue.
    for plan in catalogue.values():
        assert plan.price_ngn > 0
        assert plan.duration_days > 0
        assert plan.code.startswith(("premium_", "vip_"))
