"""adaptive asset-specific strategy intelligence foundation

Revision ID: 0025_adaptive_strategy
Revises: 0024_ml_rejected_delivery
Create Date: 2026-07-28
"""
from alembic import op
revision="0025_adaptive_strategy";down_revision="0024_ml_rejected_delivery";branch_labels=None;depends_on=None

def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_strategy_specs(id BIGSERIAL PRIMARY KEY,strategy_id VARCHAR(128) NOT NULL,version VARCHAR(64) NOT NULL,parent_version VARCHAR(64),family VARCHAR(64) NOT NULL,creation_source VARCHAR(32) NOT NULL DEFAULT 'deterministic',state VARCHAR(32) NOT NULL DEFAULT 'DRAFT',spec JSONB NOT NULL DEFAULT '{}'::jsonb,dataset_version VARCHAR(128),feature_version VARCHAR(128),approved_by BIGINT,approved_at TIMESTAMP,suspension_reason TEXT,created_at TIMESTAMP NOT NULL DEFAULT NOW(),updated_at TIMESTAMP NOT NULL DEFAULT NOW(),CONSTRAINT uq_adaptive_strategy_spec UNIQUE(strategy_id,version))""")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_asset_profiles(profile_id VARCHAR(128) PRIMARY KEY,asset VARCHAR(32) NOT NULL,asset_class VARCHAR(32) NOT NULL,version INTEGER NOT NULL,state VARCHAR(32) NOT NULL DEFAULT 'DRAFT',source_scope VARCHAR(32) NOT NULL DEFAULT 'asset',is_current BOOLEAN NOT NULL DEFAULT FALSE,preferred_families JSONB NOT NULL DEFAULT '[]'::jsonb,penalised_families JSONB NOT NULL DEFAULT '[]'::jsonb,disabled_families JSONB NOT NULL DEFAULT '[]'::jsonb,preferred_timeframes JSONB NOT NULL DEFAULT '[]'::jsonb,preferred_sessions JSONB NOT NULL DEFAULT '[]'::jsonb,avoided_sessions JSONB NOT NULL DEFAULT '[]'::jsonb,regime_weights JSONB NOT NULL DEFAULT '{}'::jsonb,family_weights JSONB NOT NULL DEFAULT '{}'::jsonb,minimum_confidence DOUBLE PRECISION NOT NULL DEFAULT 0.70,minimum_reward_risk DOUBLE PRECISION NOT NULL DEFAULT 1.5,maximum_score_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.15,minimum_score_multiplier DOUBLE PRECISION NOT NULL DEFAULT 0.85,data_sufficiency_score DOUBLE PRECISION NOT NULL DEFAULT 0,sample_size INTEGER NOT NULL DEFAULT 0,parent_profile_id VARCHAR(128),rollback_profile_id VARCHAR(128),metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMP NOT NULL DEFAULT NOW(),updated_at TIMESTAMP NOT NULL DEFAULT NOW(),CONSTRAINT uq_adaptive_asset_profile_version UNIQUE(asset,version))""")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_adaptive_asset_profile_current ON adaptive_asset_profiles(asset) WHERE is_current=TRUE")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adaptive_asset_profile_lookup ON adaptive_asset_profiles(asset,asset_class,state,is_current)")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_signal_evidence(id BIGSERIAL PRIMARY KEY,signal_id VARCHAR(36) NOT NULL REFERENCES signals(signal_id) ON DELETE CASCADE,asset VARCHAR(32) NOT NULL,timeframe VARCHAR(8) NOT NULL,strategy_id VARCHAR(128) NOT NULL,strategy_version VARCHAR(64) NOT NULL,family VARCHAR(64) NOT NULL,direction VARCHAR(16) NOT NULL,setup_type VARCHAR(128) NOT NULL,confidence DOUBLE PRECISION NOT NULL,raw_score DOUBLE PRECISION NOT NULL,evidence_quality VARCHAR(24) NOT NULL DEFAULT 'genuine',profile_id VARCHAR(128),profile_version INTEGER,regime VARCHAR(32),data_quality JSONB NOT NULL DEFAULT '{}'::jsonb,evidence JSONB NOT NULL DEFAULT '{}'::jsonb,conflicts JSONB NOT NULL DEFAULT '[]'::jsonb,duplicate_fingerprint VARCHAR(64) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT NOW(),CONSTRAINT uq_adaptive_signal_evidence UNIQUE(signal_id,duplicate_fingerprint))""")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adaptive_signal_evidence_asset_family ON adaptive_signal_evidence(asset,family,timeframe,created_at DESC)")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_signal_sequences(id BIGSERIAL PRIMARY KEY,signal_id VARCHAR(36) NOT NULL REFERENCES signals(signal_id) ON DELETE CASCADE,asset VARCHAR(32) NOT NULL,timeframe VARCHAR(8) NOT NULL,sequence_hash VARCHAR(64) NOT NULL,candle_count INTEGER NOT NULL,start_time_ms BIGINT,end_time_ms BIGINT,provider VARCHAR(64),evidence_stage VARCHAR(24) NOT NULL DEFAULT 'pre_signal',summary JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMP NOT NULL DEFAULT NOW(),CONSTRAINT uq_adaptive_signal_sequence UNIQUE(signal_id,timeframe,evidence_stage,sequence_hash))""")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adaptive_signal_sequences_hash ON adaptive_signal_sequences(asset,timeframe,sequence_hash)")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_dataset_versions(dataset_version VARCHAR(128) PRIMARY KEY,content_hash VARCHAR(64) NOT NULL UNIQUE,row_count INTEGER NOT NULL DEFAULT 0,first_decision_at TIMESTAMP,last_decision_at TIMESTAMP,evidence_categories JSONB NOT NULL DEFAULT '[]'::jsonb,assets JSONB NOT NULL DEFAULT '[]'::jsonb,sequence_coverage DOUBLE PRECISION NOT NULL DEFAULT 0,manifest JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMP NOT NULL DEFAULT NOW())""")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_feature_versions(feature_version VARCHAR(128) PRIMARY KEY,content_hash VARCHAR(64) NOT NULL UNIQUE,component_versions JSONB NOT NULL DEFAULT '{}'::jsonb,feature_schema JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMP NOT NULL DEFAULT NOW())""")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_walk_forward_runs(run_id VARCHAR(64) PRIMARY KEY,profile_id VARCHAR(128),dataset_version VARCHAR(128) NOT NULL,feature_version VARCHAR(128) NOT NULL,status VARCHAR(32) NOT NULL,started_at TIMESTAMP NOT NULL DEFAULT NOW(),completed_at TIMESTAMP,config JSONB NOT NULL DEFAULT '{}'::jsonb,metrics JSONB NOT NULL DEFAULT '{}'::jsonb,folds JSONB NOT NULL DEFAULT '[]'::jsonb,error TEXT)""")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adaptive_wfo_profile_dataset ON adaptive_walk_forward_runs(profile_id,dataset_version,created_at DESC)")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_optimisation_runs(run_id VARCHAR(64) PRIMARY KEY,status VARCHAR(32) NOT NULL,mode VARCHAR(32) NOT NULL,dataset_version VARCHAR(128),feature_version VARCHAR(128),started_at TIMESTAMP NOT NULL DEFAULT NOW(),completed_at TIMESTAMP,config JSONB NOT NULL DEFAULT '{}'::jsonb,summary JSONB NOT NULL DEFAULT '{}'::jsonb,error TEXT)""")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_promotion_events(id BIGSERIAL PRIMARY KEY,profile_id VARCHAR(128) NOT NULL,from_state VARCHAR(32),to_state VARCHAR(32) NOT NULL,decision VARCHAR(32) NOT NULL,reasons JSONB NOT NULL DEFAULT '[]'::jsonb,metrics JSONB NOT NULL DEFAULT '{}'::jsonb,actor_telegram_user_id BIGINT,idempotency_key VARCHAR(128) UNIQUE,created_at TIMESTAMP NOT NULL DEFAULT NOW())""")
    op.execute("""CREATE TABLE IF NOT EXISTS adaptive_drift_events(id BIGSERIAL PRIMARY KEY,asset VARCHAR(32) NOT NULL,profile_id VARCHAR(128),drift_type VARCHAR(64) NOT NULL,severity VARCHAR(16) NOT NULL,metrics JSONB NOT NULL DEFAULT '{}'::jsonb,resolution VARCHAR(64),created_at TIMESTAMP NOT NULL DEFAULT NOW(),resolved_at TIMESTAMP)""")

def downgrade():
    for table in ('adaptive_drift_events','adaptive_promotion_events','adaptive_optimisation_runs','adaptive_walk_forward_runs','adaptive_feature_versions','adaptive_dataset_versions','adaptive_signal_sequences','adaptive_signal_evidence','adaptive_asset_profiles','adaptive_strategy_specs'):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
