from __future__ import annotations

import logging
import os
import time
import threading
from contextlib import contextmanager
from typing import Any, Iterator

from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest

logger = logging.getLogger(__name__)

try:  # Optional dependency; the service must still run without OTel installed.
    from opentelemetry import trace
    from opentelemetry.sdk.resources import Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter

    try:
        from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
    except Exception:  # pragma: no cover - optional exporter
        OTLPSpanExporter = None  # type: ignore[assignment]
except Exception:  # pragma: no cover - OTel optional
    trace = None  # type: ignore[assignment]
    Resource = None  # type: ignore[assignment]
    TracerProvider = None  # type: ignore[assignment]
    BatchSpanProcessor = None  # type: ignore[assignment]
    ConsoleSpanExporter = None  # type: ignore[assignment]
    OTLPSpanExporter = None  # type: ignore[assignment]

_TRACER_LOCK = threading.Lock()
_TRACER: Any = None
_TRACER_PROVIDER: Any = None
_TRACER_INITIALIZED = False

SERVICE_UP = Gauge("signalrank_service_up", "Service readiness indicator")
ENGINE_CYCLE_SECONDS = Histogram("signalrank_engine_cycle_seconds", "Engine loop cycle duration in seconds", buckets=(0.1, 0.25, 0.5, 1, 2, 5, 10, 30, 60))
ENGINE_TASK_SECONDS = Histogram(
    "signalrank_engine_task_seconds",
    "Per-asset/timeframe engine task duration in seconds",
    labelnames=("asset", "timeframe", "outcome"),
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 30),
)
SIGNAL_DISPATCH_SECONDS = Histogram(
    "signalrank_signal_dispatch_seconds",
    "Telegram dispatch duration in seconds",
    labelnames=("tier", "regime", "status"),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10),
)
SIGNAL_DISPATCH_TOTAL = Counter(
    "signalrank_signal_dispatch_total",
    "Signal dispatch attempts and outcomes",
    labelnames=("tier", "regime", "status"),
)
SIGNAL_GENERATED_TOTAL = Counter(
    "signalrank_signal_generated_total",
    "Signals generated by the engine",
    labelnames=("asset", "timeframe"),
)
ML_CONFIDENCE = Histogram(
    "signalrank_ml_confidence",
    "Observed ML confidence/probability distribution",
    buckets=(0.0, 0.1, 0.2, 0.35, 0.5, 0.65, 0.8, 0.9, 0.95, 1.0),
)
HTTP_REQUEST_SECONDS = Histogram(
    "signalrank_http_request_seconds",
    "HTTP request latency in seconds",
    labelnames=("method", "route", "status"),
    buckets=(0.005, 0.01, 0.02, 0.05, 0.1, 0.25, 0.5, 1, 2, 5),
)
EXCHANGE_API_HEALTH = Gauge(
    "signalrank_exchange_api_health",
    "Exchange API health indicator (1 healthy / 0 unhealthy)",
    labelnames=("provider",),
)
EXCHANGE_RATE_LIMIT_REMAINING = Gauge(
    "signalrank_exchange_rate_limit_remaining",
    "Remaining requests before provider rate limit",
    labelnames=("provider",),
)
EXCHANGE_RATE_LIMIT_LIMIT = Gauge(
    "signalrank_exchange_rate_limit_limit",
    "Provider rate limit quota",
    labelnames=("provider",),
)

SERVICE_UP.set(1)


def prometheus_metrics_text() -> str:
    return generate_latest().decode("utf-8", errors="replace")


def prometheus_content_type() -> str:
    return CONTENT_TYPE_LATEST


def observe_engine_cycle(seconds: float) -> None:
    try:
        ENGINE_CYCLE_SECONDS.observe(max(0.0, float(seconds)))
    except Exception:
        logger.debug("[telemetry] failed to observe engine cycle", exc_info=True)


def observe_engine_task(asset: str, timeframe: str, seconds: float, outcome: str = "ok") -> None:
    try:
        ENGINE_TASK_SECONDS.labels(asset=str(asset or "unknown"), timeframe=str(timeframe or "unknown"), outcome=str(outcome or "ok")).observe(max(0.0, float(seconds)))
    except Exception:
        logger.debug("[telemetry] failed to observe engine task", exc_info=True)


def observe_signal_dispatch(seconds: float, tier: str, regime: str | None = None, status: str = "ok") -> None:
    tier_label = str(tier or "unknown").lower()
    regime_label = str(regime or "unknown").lower()
    status_label = str(status or "ok").lower()
    try:
        SIGNAL_DISPATCH_SECONDS.labels(tier=tier_label, regime=regime_label, status=status_label).observe(max(0.0, float(seconds)))
        SIGNAL_DISPATCH_TOTAL.labels(tier=tier_label, regime=regime_label, status=status_label).inc()
    except Exception:
        logger.debug("[telemetry] failed to observe dispatch", exc_info=True)


def observe_signal_generated(asset: str, timeframe: str) -> None:
    try:
        SIGNAL_GENERATED_TOTAL.labels(asset=str(asset or "unknown").upper(), timeframe=str(timeframe or "unknown")).inc()
    except Exception:
        logger.debug("[telemetry] failed to observe generated signal", exc_info=True)


def observe_ml_confidence(value: float | None) -> None:
    if value is None:
        return
    try:
        ML_CONFIDENCE.observe(max(0.0, min(1.0, float(value))))
    except Exception:
        logger.debug("[telemetry] failed to observe ml confidence", exc_info=True)


def observe_http_request(method: str, route: str, status: int | str, seconds: float) -> None:
    try:
        HTTP_REQUEST_SECONDS.labels(method=str(method or "GET").upper(), route=str(route or "unknown"), status=str(status or "200")).observe(max(0.0, float(seconds)))
    except Exception:
        logger.debug("[telemetry] failed to observe http request", exc_info=True)


def set_exchange_api_health(provider: str, healthy: bool = True) -> None:
    try:
        EXCHANGE_API_HEALTH.labels(provider=str(provider or "unknown").lower()).set(1 if healthy else 0)
    except Exception:
        logger.debug("[telemetry] failed to set exchange health", exc_info=True)


def set_exchange_rate_limit(provider: str, remaining: float | None = None, limit: float | None = None) -> None:
    provider_label = str(provider or "unknown").lower()
    try:
        if remaining is not None:
            EXCHANGE_RATE_LIMIT_REMAINING.labels(provider=provider_label).set(max(0.0, float(remaining)))
        if limit is not None:
            EXCHANGE_RATE_LIMIT_LIMIT.labels(provider=provider_label).set(max(0.0, float(limit)))
    except Exception:
        logger.debug("[telemetry] failed to set rate limit", exc_info=True)


def init_tracer(service_name: str = "signalrankai"):
    """Initialize one process-wide tracer without spawning duplicate exporters."""
    global _TRACER, _TRACER_PROVIDER, _TRACER_INITIALIZED
    if _TRACER_INITIALIZED:
        return _TRACER
    if trace is None or TracerProvider is None:
        _TRACER_INITIALIZED = True
        return None
    if str(os.getenv("OTEL_SDK_DISABLED", "0")).strip().lower() in {"1", "true", "yes", "on"}:
        _TRACER_INITIALIZED = True
        return None

    with _TRACER_LOCK:
        if _TRACER_INITIALIZED:
            return _TRACER
        try:
            resource = Resource.create({"service.name": service_name}) if Resource is not None else None
            provider = TracerProvider(resource=resource) if resource is not None else TracerProvider()
            endpoint = (os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT") or os.getenv("OTEL_EXPORTER_OTLP_TRACES_ENDPOINT") or "").strip()
            console_enabled = str(os.getenv("OTEL_CONSOLE_EXPORTER_ENABLED", "0")).strip().lower() in {"1", "true", "yes", "on"}
            if endpoint and OTLPSpanExporter is not None:
                provider.add_span_processor(BatchSpanProcessor(OTLPSpanExporter(endpoint=endpoint)))
            elif console_enabled and ConsoleSpanExporter is not None:
                provider.add_span_processor(BatchSpanProcessor(ConsoleSpanExporter()))
            trace.set_tracer_provider(provider)
            _TRACER_PROVIDER = provider
            _TRACER = trace.get_tracer(service_name)
        except Exception:
            logger.debug("[telemetry] otel init failed", exc_info=True)
            _TRACER = None
        _TRACER_INITIALIZED = True
        return _TRACER


def shutdown_tracer() -> None:
    """Flush and stop telemetry workers during service/test teardown."""
    global _TRACER, _TRACER_PROVIDER, _TRACER_INITIALIZED
    with _TRACER_LOCK:
        provider = _TRACER_PROVIDER
        _TRACER = None
        _TRACER_PROVIDER = None
        # OpenTelemetry's global provider cannot safely be replaced in the same
        # interpreter. Keep initialization closed after shutdown so repeated
        # FastAPI test lifespans cannot spawn a second exporter worker.
        _TRACER_INITIALIZED = True
    if provider is not None:
        try:
            provider.shutdown()
        except Exception:
            logger.debug("[telemetry] tracer shutdown failed", exc_info=True)


@contextmanager
def trace_span(name: str, **attributes: Any) -> Iterator[Any]:
    tracer = init_tracer()
    if trace is None or tracer is None:
        yield None
        return
    with tracer.start_as_current_span(name) as span:
        try:
            for key, value in attributes.items():
                try:
                    span.set_attribute(str(key), value)
                except Exception:
                    continue
        except Exception:
            pass
        yield span
