const API='/api/v1/platform';
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={user:null,dashboard:null,signals:[],paper:null,portfolio:null,performance:null};
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message,error=false){const el=$('#toast');el.textContent=typeof message==='string'?message:JSON.stringify(message);el.style.borderColor=error?'rgba(255,107,117,.7)':'rgba(100,240,180,.5)';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4000)}
function cookie(name){return document.cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=')||''}
async function request(path,options={}){const method=String(options.method||'GET').toUpperCase();const headers={'Content-Type':'application/json',...(options.headers||{})};if(!['GET','HEAD','OPTIONS'].includes(method)){const csrf=decodeURIComponent(cookie('sr_csrf'));if(csrf)headers['X-CSRF-Token']=csrf}const response=await fetch(API+path,{credentials:'include',headers,...options});let data={};try{data=await response.json()}catch{}if(!response.ok){const detail=data.detail;throw new Error(typeof detail==='string'?detail:(detail?.message||detail?.code||JSON.stringify(detail)||`Request failed (${response.status})`))}return data}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function fmt(value,digits=2){const number=Number(value||0);return Number.isFinite(number)?number.toLocaleString(undefined,{maximumFractionDigits:digits}):'—'}
function time(value){if(!value)return'—';return new Date(value).toLocaleString()}
function statusClass(value){const v=String(value||'').toLowerCase();return ['tp1','tp2','tp3','win','open','active'].some(x=>v.includes(x))?'positive':['sl','loss','closed_sl'].some(x=>v.includes(x))?'negative':''}
function setLoggedIn(value){$('#authShell').hidden=value;$('#appShell').hidden=!value;$('#sessionNav').hidden=!value}
function setAuthTab(name){const forms={login:$('#loginForm'),register:$('#registerForm'),activate:$('#activateForm')};Object.entries(forms).forEach(([key,el])=>el.hidden=key!==name);$('#mfaForm').hidden=true;$('#passwordResetForm').hidden=true;$('#loginTab').classList.toggle('active',name==='login');$('#registerTab').classList.toggle('active',name==='register');$('#activateTab').classList.toggle('active',name==='activate')}
$('#loginTab').onclick=()=>setAuthTab('login');$('#registerTab').onclick=()=>setAuthTab('register');$('#activateTab').onclick=()=>setAuthTab('activate');
async function completeAuth(data){if(data.mfa_required){$('#loginForm').hidden=true;$('#registerForm').hidden=true;$('#activateForm').hidden=true;$('#mfaForm').hidden=false;$('#mfaForm [name="token"]').value=data.mfa_token;toast('Enter your authenticator or recovery code');return}await boot();toast('Signed in successfully')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await completeAuth(await request('/auth/login',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})}))}catch(err){toast(err.message,true)}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const data=await request('/auth/register',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})});await completeAuth(data);toast('Account created. Check your email to verify it.')}catch(err){toast(err.message,true)}};
$('#activateForm').onsubmit=async e=>{e.preventDefault();try{await completeAuth(await request('/auth/telegram/complete',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})}));history.replaceState({},'',location.pathname);toast('Telegram account activated')}catch(err){toast(err.message,true)}};
$('#mfaForm').onsubmit=async e=>{e.preventDefault();try{await completeAuth(await request('/auth/mfa/complete',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})}))}catch(err){toast(err.message,true)}};
$('#passwordResetForm').onsubmit=async e=>{e.preventDefault();try{await request('/auth/password-reset/complete',{method:'POST',body:JSON.stringify(formData(e.target))});history.replaceState({},'',location.pathname);setAuthTab('login');toast('Password reset. Sign in again.')}catch(err){toast(err.message,true)}};
$('#magicLinkButton').onclick=async()=>{const email=prompt('Enter your account email');if(!email)return;try{await request('/auth/magic-link/request',{method:'POST',body:JSON.stringify({email})});toast('If the account exists, a sign-in link was queued.')}catch(err){toast(err.message,true)}};
$('#forgotPasswordButton').onclick=async()=>{const email=prompt('Enter your account email');if(!email)return;try{await request('/auth/password-reset/request',{method:'POST',body:JSON.stringify({email})});toast('If the account exists, reset instructions were queued.')}catch(err){toast(err.message,true)}};
function showView(name){$$('.view').forEach(el=>el.hidden=true);const target=$(`#${name}View`);if(target)target.hidden=false;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const loaders={overview:loadOverview,signals:loadSignals,markets:searchMarkets,paper:loadPaper,portfolio:loadPortfolio,performance:loadPerformance,journal:loadJournal,support:loadSupport,account:loadAccount};loaders[name]?.().catch(err=>toast(err.message,true))}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
async function boot(){try{const me=await request('/me');state.user=me.user;setLoggedIn(true);renderProfile();await Promise.all([loadOverview(),loadSignals(),loadPaper()]);const invite=new URLSearchParams(location.search).get('organization_invite');if(invite){await request('/organizations/invitations/accept',{method:'POST',body:JSON.stringify({token:invite})});history.replaceState({},'',location.pathname);toast('Workspace invitation accepted')}}catch{state.user=null;setLoggedIn(false)}}
async function loadOverview(){state.dashboard=await request('/dashboard');const s=state.dashboard.summary||{};$('#welcomeTitle').textContent=`Welcome${state.user?.display_name?`, ${state.user.display_name.split(' ')[0]}`:''}`;$('#accountSubtitle').textContent='Your signals, paper portfolio and market intelligence in one place.';$('#tierBadge').textContent=String(state.user?.tier||'free').toUpperCase();const cards=[['Delivered signals',s.delivered_signals],['Open positions',s.open_positions],['Paper cash',`$${fmt(s.paper_cash)}`],['Unrealized P/L',`$${fmt(s.unrealized_pnl)}`]];$('#summaryCards').innerHTML=cards.map(([k,v])=>`<div class="metric-card"><small>${esc(k)}</small><strong>${esc(v??0)}</strong></div>`).join('');renderOverviewLists()}
async function loadSignals(){const asset=$('#signalAssetFilter')?.value?.trim()||'';const status=$('#signalStatusFilter')?.value||'';const qs=new URLSearchParams({limit:'50'});if(asset)qs.set('asset',asset);if(status)qs.set('status',status);state.signals=(await request('/signals?'+qs)).signals||[];renderSignals();renderOverviewLists()}
function renderOverviewLists(){const recent=state.signals.slice(0,5);$('#latestSignals').innerHTML=recent.length?recent.map(s=>`<div class="list-row"><div><strong>${esc(s.asset)} ${esc(String(s.direction).toUpperCase())}</strong><small>${esc(s.timeframe)} · ${esc(s.strategy_name||'Strategy')}</small></div><div class="${statusClass(s.outcome_status)}">${esc(s.outcome_status||'Pending')}</div></div>`).join(''):'<p>No confirmed signals yet.</p>';const positions=(state.paper?.positions||[]).filter(p=>p.status==='open').slice(0,5);$('#overviewPositions').innerHTML=positions.length?positions.map(p=>`<div class="list-row"><div><strong>${esc(p.asset)} ${esc(String(p.direction).toUpperCase())}</strong><small>Entry ${fmt(p.fill_entry,6)}</small></div><div class="${Number(p.unrealized_pnl)>=0?'positive':'negative'}">$${fmt(p.unrealized_pnl)}</div></div>`).join(''):'<p>No open paper positions.</p>'}
function renderSignals(){const rows=state.signals;$('#signalsTable').innerHTML=rows.length?`<table><thead><tr><th>Asset</th><th>Direction</th><th>Timeframe</th><th>Entry</th><th>Stop</th><th>Score</th><th>Strategy</th><th>Outcome</th><th>Delivered</th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${esc(s.asset)}</strong><br><small>${esc(s.display_id||String(s.signal_id).slice(0,8))}</small></td><td>${esc(String(s.direction).toUpperCase())}</td><td>${esc(s.timeframe)}</td><td>${fmt(s.entry,6)}</td><td>${fmt(s.stop_loss,6)}</td><td>${fmt(s.score,1)}</td><td>${esc(s.strategy_name||'—')}</td><td class="${statusClass(s.outcome_status)}">${esc(s.outcome_status||s.status||'Pending')}</td><td>${time(s.delivered_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="panel">No delivery-proven signals match this view.</div>'}
$('#refreshSignals').onclick=loadSignals;$('#signalAssetFilter').onchange=loadSignals;$('#signalStatusFilter').onchange=loadSignals;
async function searchMarkets(){const qs=new URLSearchParams({q:$('#marketSearch')?.value||'',limit:'60'});const assetClass=$('#assetClassFilter')?.value;if(assetClass)qs.set('asset_class',assetClass);const rows=(await request('/instruments/search?'+qs)).instruments||[];$('#marketResults').innerHTML=rows.length?rows.map(i=>`<article class="market-card"><h3>${esc(i.display_symbol||i.canonical_symbol)}</h3><p>${esc(i.asset_class)} · ${esc(i.instrument_type)}</p><p>${i.tradable?'Tradable':'Analysis only'} · ${esc(i.discovery_status)}</p><div class="provider-pills">${(i.providers||[]).map(p=>`<span>${esc(p)}</span>`).join('')}</div></article>`).join(''):'<p>No registry instruments found. Run provider discovery after migration.</p>'}
$('#searchMarkets').onclick=()=>searchMarkets().catch(e=>toast(e.message,true));$('#marketSearch').onkeydown=e=>{if(e.key==='Enter')searchMarkets().catch(x=>toast(x.message,true))};
async function loadPaper(){state.paper=await request('/paper');const a=state.paper.account||{};$('#paperAccount').innerHTML=[['Cash balance',`$${fmt(a.cash_balance)}`],['Realized P/L',`$${fmt(a.realized_pnl)}`],['Risk per trade',`${fmt(a.risk_pct)}%`],['Auto paper',a.auto_trade_enabled?'Enabled':'Disabled']].map(([k,v])=>`<div class="metric-card"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');const rows=state.paper.positions||[];$('#paperPositions').innerHTML=rows.length?`<table><thead><tr><th>Asset</th><th>Status</th><th>Direction</th><th>Entry</th><th>Current</th><th>Quantity</th><th>Unrealized</th><th>Opened</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.asset)}</td><td>${esc(p.status)}</td><td>${esc(String(p.direction).toUpperCase())}</td><td>${fmt(p.fill_entry,6)}</td><td>${fmt(p.current_price,6)}</td><td>${fmt(p.quantity,6)}</td><td class="${Number(p.unrealized_pnl)>=0?'positive':'negative'}">$${fmt(p.unrealized_pnl)}</td><td>${time(p.opened_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="panel">No paper positions yet.</div>';renderOverviewLists()}
async function loadPortfolio(){state.portfolio=await request('/portfolio');const a=state.portfolio.account||{};$('#portfolioSummary').innerHTML=[['Equity',`$${fmt(state.portfolio.equity)}`],['Cash',`$${fmt(a.cash_balance)}`],['Realized',`$${fmt(a.realized_pnl)}`],['Open exposures',(state.portfolio.exposures||[]).length]].map(([k,v])=>`<div class="metric-card"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');const rows=state.portfolio.exposures||[];$('#portfolioExposures').innerHTML=rows.length?`<table><thead><tr><th>Asset</th><th>Class</th><th>Direction</th><th>Positions</th><th>Notional</th><th>Unrealized</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.asset)}</td><td>${esc(r.asset_class)}</td><td>${esc(r.direction)}</td><td>${esc(r.positions)}</td><td>$${fmt(r.notional)}</td><td class="${Number(r.unrealized_pnl)>=0?'positive':'negative'}">$${fmt(r.unrealized_pnl)}</td></tr>`).join('')}</tbody></table>`:'<div class="panel">No open exposure.</div>'}
async function loadPerformance(){state.performance=await request('/performance');const s=state.performance.summary||{};$('#performanceSummary').innerHTML=[['Signals',s.signals||0],['Wins',s.wins||0],['Losses',s.losses||0],['Win rate',s.win_rate==null?'Not enough data':`${fmt(Number(s.win_rate)*100,1)}%`],['Average R',fmt(s.average_r,2)],['Total R',fmt(s.total_r,2)]].map(([k,v])=>`<div class="metric-card"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');const rows=state.performance.breakdown||[];$('#performanceBreakdown').innerHTML=rows.length?`<table><thead><tr><th>Asset</th><th>Timeframe</th><th>Signals</th><th>Average R</th><th>Total R</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.asset)}</td><td>${esc(r.timeframe)}</td><td>${esc(r.signals)}</td><td>${fmt(r.average_r)}</td><td>${fmt(r.total_r)}</td></tr>`).join('')}</tbody></table>`:'<div class="panel">No proof-backed performance rows yet.</div>'}
async function loadJournal(){const rows=(await request('/journal?limit=100')).entries||[];$('#journalEntries').innerHTML=rows.length?rows.map(entry=>`<div class="list-row"><div><strong>${esc(entry.title||'Journal entry')}</strong><small>${time(entry.occurred_at)} · ${esc(entry.emotion||'No emotion tag')}${entry.result_r==null?'':` · ${fmt(entry.result_r)}R`}</small><p>${esc(entry.notes||'')}</p></div><button class="danger journal-delete" data-id="${esc(entry.journal_entry_id)}">Delete</button></div>`).join(''):'<p>No journal entries yet.</p>';$$('.journal-delete').forEach(button=>button.onclick=async()=>{if(!confirm('Delete this journal entry?'))return;await request('/journal/'+encodeURIComponent(button.dataset.id),{method:'DELETE'});loadJournal()})}
$('#journalForm').onsubmit=async e=>{e.preventDefault();const raw=formData(e.target);const payload={title:raw.title||null,notes:raw.notes||'',emotion:raw.emotion||null,mistake_category:raw.mistake_category||null,plan_adherence:raw.plan_adherence?Number(raw.plan_adherence):null,result_r:raw.result_r?Number(raw.result_r):null,tags:String(raw.tags||'').split(',').map(x=>x.trim()).filter(Boolean)};try{await request('/journal',{method:'POST',body:JSON.stringify(payload)});e.target.reset();await loadJournal();toast('Journal entry saved')}catch(err){toast(err.message,true)}};
async function loadSupport(){const rows=(await request('/support/tickets')).tickets||[];$('#supportTickets').innerHTML=rows.length?rows.map(t=>`<div class="list-row"><div><strong>${esc(t.subject)}</strong><small>${esc(t.category)} · ${esc(t.priority)} · ${time(t.updated_at)}</small></div><span>${esc(t.status)}</span></div>`).join(''):'<p>No support tickets.</p>'}
$('#supportForm').onsubmit=async e=>{e.preventDefault();try{await request('/support/tickets',{method:'POST',body:JSON.stringify(formData(e.target))});e.target.reset();await loadSupport();toast('Support ticket created')}catch(err){toast(err.message,true)}};
function renderProfile(){const u=state.user||{};const entries=[['Public ID',u.public_user_id],['Email',u.primary_email||'Not set'],['Email verified',u.email_verified_at?'Yes':'No'],['Telegram',u.telegram_user_id?'Linked':'Not linked'],['Tier',String(u.tier||'free').toUpperCase()],['Timezone',u.timezone||'UTC'],['Account status',u.account_status]];$('#profileDetails').innerHTML=entries.map(([k,v])=>`<div class="detail-row"><span>${esc(k)}</span><strong>${esc(v||'—')}</strong></div>`).join('');const form=$('#profileForm');if(form){['display_name','country','timezone','preferred_currency','max_risk_percentage','max_daily_drawdown_pct'].forEach(name=>{if(form.elements[name])form.elements[name].value=u[name]??''})}}
$('#profileForm').onsubmit=async e=>{e.preventDefault();const raw=formData(e.target);const payload={};for(const [k,v] of Object.entries(raw)){if(v!=='')payload[k]=['max_risk_percentage','max_daily_drawdown_pct'].includes(k)?Number(v):v}try{state.user=(await request('/profile',{method:'PATCH',body:JSON.stringify(payload)})).user;renderProfile();toast('Profile updated')}catch(err){toast(err.message,true)}};
async function loadDeveloperAccess(){try{const entitlements=await request('/entitlements');const allowed=(entitlements.features||[]).includes('rest_api');$('#developerPanel').hidden=!allowed;if(!allowed)return;const keys=await request('/api-keys');$('#apiKeyList').innerHTML=(keys.api_keys||[]).map(key=>`<div class="list-row"><div><strong>${esc(key.name)}</strong><small>${esc(key.key_prefix)} · ${key.active?'Active':'Revoked'} · last used ${time(key.last_used_at)}</small></div></div>`).join('')||'<p>No API keys.</p>'}catch{$('#developerPanel').hidden=true}}
$('#createApiKeyButton').onclick=async()=>{const name=prompt('Name this API key','Signals client');if(!name)return;try{const data=await request('/api-keys',{method:'POST',body:JSON.stringify({name,scopes:['signals:read'],expires_in_days:90})});$('#apiKeyResult').innerHTML=`<div class="detail-row"><span>Copy now</span><strong><code>${esc(data.api_key)}</code></strong></div><p>${esc(data.warning)}</p>`;await loadDeveloperAccess()}catch(err){toast(err.message,true)}};
async function loadBillingProducts(){const data=await request('/billing/products');const products=data.products||[];$('#billingProducts').innerHTML=products.length?products.map(p=>`<article class="metric-card"><small>${esc(String(p.tier).toUpperCase())}</small><strong>${esc(p.display_name)}</strong><p>${esc(p.currency)} ${fmt(p.price_ngn,0)} · ${esc(p.duration_days)} days</p><button class="primary billing-checkout" data-product="${esc(p.product_id)}">Choose plan</button></article>`).join(''):'<p>No public checkout products are available.</p>';$$('.billing-checkout').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const checkout=await request('/billing/checkout',{method:'POST',body:JSON.stringify({product_id:button.dataset.product,currency:'NGN'})});if(!checkout.authorization_url)throw new Error('Checkout URL unavailable');location.assign(checkout.authorization_url)}catch(err){button.disabled=false;toast(err.message,true)}})}
async function loadAccount(){const [devices,prefs,mfa,billing]=await Promise.all([request('/devices'),request('/notifications/preferences'),request('/security/mfa'),request('/billing')]);await Promise.all([loadDeveloperAccess(),loadBillingProducts()]);$('#sessionList').innerHTML=(devices.sessions||[]).map(s=>`<div class="list-row"><div><strong>${s.session_id===devices.current_session_id?'Current session':'Signed-in session'}</strong><small>${time(s.last_used_at)} · expires ${time(s.expires_at)}</small></div>${s.session_id===devices.current_session_id?'<span>Current</span>':`<button class="danger revoke-session" data-id="${esc(s.session_id)}">Revoke</button>`}</div>`).join('')||'<p>No sessions.</p>';$$('.revoke-session').forEach(b=>b.onclick=async()=>{await request('/devices/'+encodeURIComponent(b.dataset.id),{method:'DELETE'});loadAccount()});const p=prefs.preferences||{};['telegram_enabled','web_enabled','email_enabled','push_enabled'].forEach(name=>{const input=$(`#notificationForm [name="${name}"]`);if(input)input.checked=Boolean(p[name])});$('#emailVerificationPanel').innerHTML=state.user.email_verified_at?'<p class="positive">Email verified</p>':'<button id="verifyEmailButton" class="ghost">Send verification email</button>';$('#verifyEmailButton')?.addEventListener('click',async()=>{await request('/auth/email-verification/request',{method:'POST',body:'{}'});toast('Verification email queued')});$('#mfaPanel').innerHTML=mfa.enabled?`<div class="detail-row"><span>Authenticator MFA</span><strong>Enabled</strong></div><button id="disableMfaButton" class="danger">Disable MFA</button>`:`<div class="detail-row"><span>Authenticator MFA</span><strong>Disabled</strong></div><button id="setupMfaButton" class="primary">Set up MFA</button>`;$('#setupMfaButton')?.addEventListener('click',setupMfa);$('#disableMfaButton')?.addEventListener('click',disableMfa);$('#billingHistory').innerHTML=(billing.receipts||[]).map(r=>`<div class="list-row"><div><strong>${esc(r.plan)}</strong><small>${esc(r.receipt_number)} · ${time(r.payment_date)}</small></div><span>${esc(r.currency)} ${fmt(r.amount)}</span></div>`).join('')||'<p>No payment receipts.</p>';renderProfile()}
async function setupMfa(){try{const setup=await request('/security/mfa/setup',{method:'POST',body:'{}'});const code=prompt(`Add this secret to your authenticator:\n${setup.secret}\n\nThen enter the 6-digit code.`);if(!code)return;const result=await request('/security/mfa/enable',{method:'POST',body:JSON.stringify({code})});alert('Store these recovery codes offline:\n\n'+result.recovery_codes.join('\n'));await loadAccount();toast('MFA enabled')}catch(err){toast(err.message,true)}}
async function disableMfa(){const code=prompt('Enter an authenticator or recovery code to disable MFA');if(!code)return;try{await request('/security/mfa/disable',{method:'POST',body:JSON.stringify({code})});await loadAccount();toast('MFA disabled')}catch(err){toast(err.message,true)}}
$('#connectTelegramButton').onclick=async()=>{try{const data=await request('/account/telegram-link',{method:'POST',body:'{}'});const result=$('#telegramLinkResult');result.hidden=false;result.innerHTML=`<div class="detail-row"><span>One-time code</span><strong>${esc(data.code)}</strong></div><p>Send <code>/link ${esc(data.code)}</code> to the bot before ${time(data.expires_at)}.</p>${data.telegram_deep_link?`<p><a class="primary link-button" href="${esc(data.telegram_deep_link)}" target="_blank" rel="noopener">Open Telegram</a></p>`:''}`;toast('Telegram link code created')}catch(err){toast(err.message,true)}};
$('#notificationForm').onsubmit=async e=>{e.preventDefault();const payload={};['telegram_enabled','web_enabled','email_enabled','push_enabled'].forEach(name=>payload[name]=e.target.elements[name].checked);try{await request('/notifications/preferences',{method:'PUT',body:JSON.stringify(payload)});toast('Notification preferences saved')}catch(err){toast(err.message,true)}};
async function logout(){try{await request('/auth/logout',{method:'POST',body:'{}'})}finally{state.user=null;setLoggedIn(false);location.reload()}}
$('#logoutButton').onclick=logout;$('#logoutAllButton').onclick=async()=>{if(!confirm('Sign out every device?'))return;try{await request('/auth/logout-all',{method:'POST',body:'{}'});location.reload()}catch(err){toast(err.message,true)}};
async function processUrlActions(){const qs=new URLSearchParams(location.search);const token=qs.get('token');if(token){setAuthTab('activate');$('#activationCredential').value=token}const reset=qs.get('password_reset');if(reset){setAuthTab('login');$('#loginForm').hidden=true;$('#passwordResetForm').hidden=false;$('#passwordResetForm [name="token"]').value=reset}const verify=qs.get('verify_email');if(verify){try{await request('/auth/email-verification/complete',{method:'POST',body:JSON.stringify({token:verify,client_type:'web'})});history.replaceState({},'',location.pathname);toast('Email verified')}catch(err){toast(err.message,true)}}const magic=qs.get('magic_login');if(magic){try{await completeAuth(await request('/auth/magic-link/complete',{method:'POST',body:JSON.stringify({token:magic,client_type:'web'})}));history.replaceState({},'',location.pathname)}catch(err){toast(err.message,true)}}}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/app/service-worker.js').catch(()=>{}))}
processUrlActions().then(boot);
