const API='/api/v1/platform';
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={user:null,dashboard:null,signals:[],paper:null};
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.style.borderColor=error?'rgba(255,107,117,.7)':'rgba(100,240,180,.5)';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function cookie(name){return document.cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=')||''}async function request(path,options={}){const method=String(options.method||'GET').toUpperCase();const headers={'Content-Type':'application/json',...(options.headers||{})};if(!['GET','HEAD','OPTIONS'].includes(method)){const csrf=decodeURIComponent(cookie('sr_csrf'));if(csrf)headers['X-CSRF-Token']=csrf}const response=await fetch(API+path,{credentials:'include',headers,...options});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.detail||data.message||`Request failed (${response.status})`);return data}
function setAuthTab(name){const forms={login:$('#loginForm'),register:$('#registerForm'),activate:$('#activateForm')};Object.entries(forms).forEach(([key,el])=>el.hidden=key!==name);$('#loginTab').classList.toggle('active',name==='login');$('#registerTab').classList.toggle('active',name==='register');$('#activateTab').classList.toggle('active',name==='activate')}
$('#loginTab').onclick=()=>setAuthTab('login');$('#registerTab').onclick=()=>setAuthTab('register');$('#activateTab').onclick=()=>setAuthTab('activate');
function formData(form){return Object.fromEntries(new FormData(form).entries())}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await request('/auth/login',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})});await boot();toast('Signed in successfully')}catch(err){toast(err.message,true)}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{await request('/auth/register',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})});await boot();toast('Account created')}catch(err){toast(err.message,true)}};
$('#activateForm').onsubmit=async e=>{e.preventDefault();try{await request('/auth/telegram/complete',{method:'POST',body:JSON.stringify({...formData(e.target),client_type:'web'})});history.replaceState({},'',location.pathname);await boot();toast('Telegram account activated in the app')}catch(err){toast(err.message,true)}};
function setLoggedIn(loggedIn){$('#authShell').hidden=loggedIn;$('#appShell').hidden=!loggedIn;$('#sessionNav').hidden=!loggedIn}
function showView(name){$$('.view').forEach(el=>el.hidden=true);$(`#${name}View`).hidden=false;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='signals')loadSignals();if(name==='markets')searchMarkets();if(name==='paper')loadPaper();if(name==='journal')loadJournal();if(name==='account')loadAccount()}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function fmt(value,digits=2){const number=Number(value||0);return Number.isFinite(number)?number.toLocaleString(undefined,{maximumFractionDigits:digits}):'—'}
function time(value){if(!value)return'—';return new Date(value).toLocaleString()}
function statusClass(value){const v=String(value||'').toLowerCase();return ['tp1','tp2','tp3','win','open','active'].some(x=>v.includes(x))?'positive':['sl','loss','closed_sl'].some(x=>v.includes(x))?'negative':''}
async function boot(){try{const me=await request('/me');state.user=me.user;setLoggedIn(true);await Promise.all([loadOverview(),loadSignals(),loadPaper()]);renderProfile()}catch{setLoggedIn(false)}}
async function loadOverview(){state.dashboard=await request('/dashboard');const s=state.dashboard.summary||{};$('#welcomeTitle').textContent=`Welcome${state.user?.display_name?`, ${state.user.display_name.split(' ')[0]}`:''}`;$('#accountSubtitle').textContent='Your signals, paper portfolio and market intelligence in one place.';$('#tierBadge').textContent=String(state.user?.tier||'free').toUpperCase();const cards=[['Delivered signals',s.delivered_signals],['Open positions',s.open_positions],['Paper cash',`$${fmt(s.paper_cash)}`],['Unrealized P/L',`$${fmt(s.unrealized_pnl)}`]];$('#summaryCards').innerHTML=cards.map(([k,v])=>`<div class="metric-card"><small>${k}</small><strong>${v??0}</strong></div>`).join('');renderOverviewLists()}
async function loadSignals(){const asset=$('#signalAssetFilter')?.value?.trim()||'';const status=$('#signalStatusFilter')?.value||'';const qs=new URLSearchParams({limit:'50'});if(asset)qs.set('asset',asset);if(status)qs.set('status',status);const data=await request('/signals?'+qs);state.signals=data.signals||[];renderSignals();renderOverviewLists()}
function renderOverviewLists(){const recent=(state.signals||[]).slice(0,5);$('#latestSignals').innerHTML=recent.length?recent.map(s=>`<div class="list-row"><div><strong>${s.asset} ${String(s.direction).toUpperCase()}</strong><small>${s.timeframe} · ${s.strategy_name||'Strategy'}</small></div><div class="${statusClass(s.outcome_status)}">${s.outcome_status||'Pending'}</div></div>`).join(''):'<p>No confirmed signals yet.</p>';const positions=(state.paper?.positions||[]).filter(p=>p.status==='open').slice(0,5);$('#overviewPositions').innerHTML=positions.length?positions.map(p=>`<div class="list-row"><div><strong>${p.asset} ${String(p.direction).toUpperCase()}</strong><small>Entry ${fmt(p.fill_entry,6)}</small></div><div class="${Number(p.unrealized_pnl)>=0?'positive':'negative'}">$${fmt(p.unrealized_pnl)}</div></div>`).join(''):'<p>No open paper positions.</p>'}
function renderSignals(){const rows=state.signals||[];$('#signalsTable').innerHTML=rows.length?`<table><thead><tr><th>Asset</th><th>Direction</th><th>Timeframe</th><th>Entry</th><th>Stop</th><th>Score</th><th>Strategy</th><th>Outcome</th><th>Delivered</th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${s.asset}</strong><br><small>${s.display_id||s.signal_id.slice(0,8)}</small></td><td>${String(s.direction).toUpperCase()}</td><td>${s.timeframe}</td><td>${fmt(s.entry,6)}</td><td>${fmt(s.stop_loss,6)}</td><td>${fmt(s.score,1)}</td><td>${s.strategy_name||'—'}</td><td class="${statusClass(s.outcome_status)}">${s.outcome_status||s.status||'Pending'}</td><td>${time(s.delivered_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="panel">No delivery-proven signals match this view.</div>'}
$('#refreshSignals').onclick=loadSignals;$('#signalAssetFilter').onchange=loadSignals;$('#signalStatusFilter').onchange=loadSignals;
async function searchMarkets(){const qs=new URLSearchParams({q:$('#marketSearch')?.value||'',limit:'60'});const assetClass=$('#assetClassFilter')?.value;if(assetClass)qs.set('asset_class',assetClass);try{const data=await request('/instruments/search?'+qs);const rows=data.instruments||[];$('#marketResults').innerHTML=rows.length?rows.map(i=>`<article class="market-card"><h3>${i.display_symbol||i.canonical_symbol}</h3><p>${i.asset_class} · ${i.instrument_type}</p><p>${i.tradable?'Tradable':'Analysis only'} · ${i.discovery_status}</p><div class="provider-pills">${(i.providers||[]).map(p=>`<span>${p}</span>`).join('')}</div></article>`).join(''):'<p>No registry instruments found. Run the provider discovery bootstrap after applying the latest migration.</p>'}catch(err){toast(err.message,true)}}
$('#searchMarkets').onclick=searchMarkets;$('#marketSearch').onkeydown=e=>{if(e.key==='Enter')searchMarkets()};
async function loadPaper(){state.paper=await request('/paper');const a=state.paper.account||{};$('#paperAccount').innerHTML=[['Cash balance',`$${fmt(a.cash_balance)}`],['Realized P/L',`$${fmt(a.realized_pnl)}`],['Risk per trade',`${fmt(a.risk_pct)}%`],['Auto paper',a.auto_trade_enabled?'Enabled':'Disabled']].map(([k,v])=>`<div class="metric-card"><small>${k}</small><strong>${v}</strong></div>`).join('');const rows=state.paper.positions||[];$('#paperPositions').innerHTML=rows.length?`<table><thead><tr><th>Asset</th><th>Status</th><th>Direction</th><th>Entry</th><th>Current</th><th>Quantity</th><th>Unrealized</th><th>Opened</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${p.asset}</td><td>${p.status}</td><td>${String(p.direction).toUpperCase()}</td><td>${fmt(p.fill_entry,6)}</td><td>${fmt(p.current_price,6)}</td><td>${fmt(p.quantity,6)}</td><td class="${Number(p.unrealized_pnl)>=0?'positive':'negative'}">$${fmt(p.unrealized_pnl)}</td><td>${time(p.opened_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="panel">No paper positions yet.</div>';renderOverviewLists()}

async function loadJournal(){try{const data=await request('/journal?limit=100');const rows=data.entries||[];$('#journalEntries').innerHTML=rows.length?rows.map(entry=>`<div class="list-row"><div><strong>${entry.title||'Journal entry'}</strong><small>${time(entry.occurred_at)} · ${entry.emotion||'No emotion tag'}${entry.result_r==null?'':` · ${fmt(entry.result_r)}R`}</small><p>${String(entry.notes||'').replace(/[<>]/g,'')}</p></div><button class="danger journal-delete" data-id="${entry.journal_entry_id}">Delete</button></div>`).join(''):'<p>No journal entries yet.</p>';$$('.journal-delete').forEach(button=>button.onclick=async()=>{if(!confirm('Delete this journal entry?'))return;await request('/journal/'+button.dataset.id,{method:'DELETE'});loadJournal()})}catch(err){toast(err.message,true)}}
$('#journalForm').onsubmit=async e=>{e.preventDefault();const raw=formData(e.target);const payload={title:raw.title||null,notes:raw.notes||'',emotion:raw.emotion||null,mistake_category:raw.mistake_category||null,plan_adherence:raw.plan_adherence?Number(raw.plan_adherence):null,result_r:raw.result_r?Number(raw.result_r):null,tags:String(raw.tags||'').split(',').map(x=>x.trim()).filter(Boolean)};try{await request('/journal',{method:'POST',body:JSON.stringify(payload)});e.target.reset();await loadJournal();toast('Journal entry saved')}catch(err){toast(err.message,true)}};
async function loadDeveloperAccess(){try{const entitlements=await request('/entitlements');const allowed=(entitlements.features||[]).includes('rest_api');$('#developerPanel').hidden=!allowed;if(!allowed)return;const keys=await request('/api-keys');$('#apiKeyList').innerHTML=(keys.api_keys||[]).map(key=>`<div class="list-row"><div><strong>${key.name}</strong><small>${key.key_prefix} · ${key.active?'Active':'Revoked'} · last used ${time(key.last_used_at)}</small></div></div>`).join('')||'<p>No API keys.</p>'}catch{$('#developerPanel').hidden=true}}
$('#createApiKeyButton').onclick=async()=>{const name=prompt('Name this API key','Signals client');if(!name)return;try{const data=await request('/api-keys',{method:'POST',body:JSON.stringify({name,scopes:['signals:read'],expires_in_days:90})});$('#apiKeyResult').innerHTML=`<div class="detail-row"><span>Copy now</span><strong><code>${data.api_key}</code></strong></div><p>${data.warning}</p>`;await loadDeveloperAccess()}catch(err){toast(err.message,true)}};
function renderProfile(){const u=state.user||{};const entries=[['Public ID',u.public_user_id],['Email',u.primary_email||'Not set'],['Telegram',u.telegram_user_id?'Linked':'Not linked'],['Tier',String(u.tier||'free').toUpperCase()],['Timezone',u.timezone||'UTC'],['Account status',u.account_status]];$('#profileDetails').innerHTML=entries.map(([k,v])=>`<div class="detail-row"><span>${k}</span><strong>${v||'—'}</strong></div>`).join('')}
async function loadAccount(){const [devices,prefs]=await Promise.all([request('/devices'),request('/notifications/preferences')]);await loadDeveloperAccess();$('#sessionList').innerHTML=(devices.sessions||[]).map(s=>`<div class="list-row"><div><strong>${s.session_id===devices.current_session_id?'Current session':'Signed-in session'}</strong><small>${time(s.last_used_at)} · expires ${time(s.expires_at)}</small></div><span>${s.revoked_at?'Revoked':'Active'}</span></div>`).join('')||'<p>No sessions.</p>';const p=prefs.preferences||{};['telegram_enabled','web_enabled','email_enabled','push_enabled'].forEach(name=>{const input=$(`#notificationForm [name="${name}"]`);if(input)input.checked=Boolean(p[name])})}

$('#connectTelegramButton').onclick=async()=>{try{const data=await request('/account/telegram-link',{method:'POST',body:'{}'});const result=$('#telegramLinkResult');result.hidden=false;result.innerHTML=`<div class="detail-row"><span>One-time code</span><strong>${data.code}</strong></div><p>Send <code>/link ${data.code}</code> to the SignalRankAI bot before ${time(data.expires_at)}.</p>${data.telegram_deep_link?`<p><a class="primary link-button" href="${data.telegram_deep_link}" target="_blank" rel="noopener">Open Telegram</a></p>`:''}`;toast('Telegram link code created')}catch(err){toast(err.message,true)}};
$('#notificationForm').onsubmit=async e=>{e.preventDefault();const payload={};['telegram_enabled','web_enabled','email_enabled','push_enabled'].forEach(name=>payload[name]=e.target.elements[name].checked);try{await request('/notifications/preferences',{method:'PUT',body:JSON.stringify(payload)});toast('Notification preferences saved')}catch(err){toast(err.message,true)}};
async function logout(){try{await request('/auth/logout',{method:'POST',body:'{}'})}finally{state.user=null;setLoggedIn(false);location.reload()}}
$('#logoutButton').onclick=logout;$('#logoutAllButton').onclick=async()=>{if(!confirm('Sign out every device?'))return;try{await request('/auth/logout-all',{method:'POST',body:'{}'});location.reload()}catch(err){toast(err.message,true)}};
const token=new URLSearchParams(location.search).get('token');if(token){setAuthTab('activate');$('#activationCredential').value=token}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/app/service-worker.js').catch(()=>{}))}
boot();
